pipeline:
  dep:
    group: docker
    image: plugins/docker
    repo: metalmatze/dep
    dockerfile: dep/Dockerfile
    secrets: [ docker_username, docker_password ]
    tag: [ latest, 0.4.1 ]
    when:
      branch: master
      event: push

  golangci-lint:
    group: docker
    image: plugins/docker
    repo: metalmatze/golangci-lint
    dockerfile: golangci-lint/Dockerfile
    secrets: [ docker_username, docker_password ]
    tag: [ latest, 1.3.7 ]
    when:
      branch: master
      event: push

  gometalinter:
    group: docker
    image: plugins/docker
    repo: metalmatze/gometalinter
    dockerfile: gometalinter/Dockerfile
    secrets: [ docker_username, docker_password ]
    tag: [ latest, 2.0.5 ]
    when:
      branch: master
      event: push

  wwhrd:
    group: docker
    image: plugins/docker
    repo: metalmatze/wwhrd
    dockerfile: wwhrd/Dockerfile
    secrets: [ docker_username, docker_password ]
    tag: [ latest, 1.9 ]
    when:
      branch: master
      event: push
